import {
  PersonStatus,
  Record,
  Person,
  RecordReference,
  AddOrUpdateRecordRequest,
  AddOrUpdateBlindedRecordRequest,
  MatchedPersonReference,
  AddOrUpdateRecordResponse,
  AddOrUpdateBlindedRecordResponse,
  GetPersonByRecordResponse,
  GetPersonByIDRequest,
  GetPersonByIDResponse,
  MatchDemographicsResponse,
  MatchDemographicsRequest,
  MatchBlindedDemographicRequest,
  MatchBlindedDemographicsResponse,
  DeleteRecordRequest,
  DeleteRecordResponse,
  MatchGuidanceRequest,
  AddMatchGuidanceRequest,
  AddMatchGuidanceResponse,
  RemoveMatchGuidanceRequest,
  RemoveMatchGuidanceResponse,
  GetPersonByRecordRequest,
  IdentityApiConfiguration,
  IdentityApi,
} from "./identity/api.js";
import { Demographic, BlindedDemographic } from "./identity/demographic.js";
import {
  HashDemographicResponse,
  LocalHashingApi,
  LocalHashingApiConfiguration
} from "./identity/localHashing.js";

export {
  PersonStatus,
  Record,
  Person,
  RecordReference,
  AddOrUpdateRecordRequest,
  AddOrUpdateBlindedRecordRequest,
  MatchedPersonReference,
  AddOrUpdateRecordResponse,
  AddOrUpdateBlindedRecordResponse,
  GetPersonByRecordResponse,
  GetPersonByIDRequest,
  GetPersonByIDResponse,
  MatchDemographicsResponse,
  MatchDemographicsRequest,
  MatchBlindedDemographicRequest,
  MatchBlindedDemographicsResponse,
  DeleteRecordRequest,
  DeleteRecordResponse,
  MatchGuidanceRequest,
  AddMatchGuidanceRequest,
  AddMatchGuidanceResponse,
  RemoveMatchGuidanceRequest,
  RemoveMatchGuidanceResponse,
  GetPersonByRecordRequest,
  IdentityApiConfiguration,
  Demographic,
  BlindedDemographic,
  HashDemographicResponse,
  LocalHashingApiConfiguration,
  IdentityApi,
  LocalHashingApi,
};