version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: weekly
    assignees:
      - "jeremytwfortune"
    groups:
      minor-patch:
        patterns: "*"
        update_types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: weekly
    assignees:
      - "jeremytwfortune"
    groups:
      minor-patch:
        patterns: "*"
        update_types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "jeremytwfortune"
    groups:
      minor-patch:
        patterns: "*"
        update_types:
          - "minor"
          - "patch"
