name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    secrets:
      ROSETTA_API_KEY:
        required: false

jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ["18", "20"]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Write Env
        shell: pwsh
        run: |
          if ("${{ secrets.ROSETTA_API_KEY }}" -eq "") {
            throw "ROSETTA_API_KEY secret is required for this workflow."
          }
          "ROSETTA_API_KEY=${{ secrets.ROSETTA_API_KEY }}" | Out-File -FilePath ./.env -Encoding utf8
      - name: Install dependencies
        working-directory: typescript
        run: npm ci
      - name: Run tests
        working-directory: typescript
        shell: pwsh
        run: npm run test

  python:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Install Python
        id: setup-python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Remove Non-Default Lock File
        working-directory: python
        id: remove-lock
        if: matrix.python-version != '3.9'
        run: rm ./poetry.lock
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Write Env
        shell: pwsh
        run: |
          if ("${{ secrets.ROSETTA_API_KEY }}" -eq "") {
            throw "ROSETTA_API_KEY secret is required for this workflow."
          }
          "ROSETTA_API_KEY=${{ secrets.ROSETTA_API_KEY }}" | Out-File -FilePath ./.env -Encoding utf8
      - name: Copy Local README
        run: cp ./README.md python/README.md
      - name: Install Dependencies
        working-directory: python
        run: poetry install --no-interaction --with "main, test"
      - name: Lint
        working-directory: python
        run: poetry run black --check .
      - name: Test
        working-directory: python
        run: poetry run pytest
